# Generated by Django 3.1.8 on 2021-06-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superhero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroes',
            name='alter_ego_name',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheroes',
            name='catchphrase',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheroes',
            name='primary_ability',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheroes',
            name='secondary_ability',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superheroes',
            name='superhero_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
