# Generated by Django 3.1.8 on 2021-06-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Superhero', '0002_auto_20210603_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroes',
            name='superhero_picture',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superheroes',
            name='catchphrase',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='superheroes',
            name='primary_ability',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='superheroes',
            name='secondary_ability',
            field=models.CharField(max_length=75),
        ),
    ]
